easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Course
        - App\Entity\Lesson
        - App\Entity\Question
        - App\Entity\Reply
        - App\Entity\Test
        - App\Entity\User




