vich_uploader:
    db_driver: orm

    mappings:
        course:
            uri_prefix: '%app.path.course_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.course_images%'
